<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Seminarverwaltung - <?php echo $title ?></title>
</head>

<body>

    <div id="gesamt">

        <div id="kopf">
            <h1>Die Seminarverwaltung - <?php echo $title ?></h1>
            <ul>
                <li style="display: inline;">
                    <a href="<?php echo $this->urlFor('seminar') ?>">Seminare</a> |
                </li>
                <li style="display: inline;">
                    <a href="<?php echo $this->urlFor('seminartermine') ?>">Seminartermine</a> |
                </li>
                <li style="display: inline;">
                    <a href="<?php echo $this->urlFor('benutzer') ?>">Benutzer</a>
                </li>
            </ul>
        </div>
            <?php if ($this->hasMessages() ): ?>
                <p style="color: green"><?php echo $this->displayMessages() ?></p>
            <?php endif; ?>
            <?php require_once $this->getTemplatePath(); ?>

        <div id="fuss">
            Der Footer
        </div>

    </div>

</body>

</html>