<?php require 'views/partials/pager.phtml' ?>

<table border="1">
    <tr>
        <th><a href="<?php echo $this->urlFor('benutzer', 'index') ?>?order_by=vorname&asc=<?php echo $asc ? 'false' : 'true' ?>">Vorname</a></th>
        <th><a href="<?php echo $this->urlFor('benutzer', 'index') ?>?order_by=name&asc=<?php echo $asc ? 'false' : 'true' ?>">Name</a></th>
        <th><a href="<?php echo $this->urlFor('benutzer', 'index') ?>?order_by=email&asc=<?php echo $asc ? 'false' : 'true' ?>">E-Mail-Adresse</a></th>
        <th><a href="<?php echo $this->urlFor('benutzer', 'index') ?>?order_by=registriert_seit&asc=<?php echo $asc ? 'false' : 'true' ?>">Registiert seit</a></th>
        <th>editieren</th>
        <th>löschen</th>
    </tr>
    <?php foreach ($benutzer as $b): ?>
        <tr>
            <td><?php echo $b->getVorname() ?></td>
            <td><?php echo $b->getName() ?></td>
            <td><?php echo $b->getEmail() ?></td>
            <td><?php echo $b->getRegistriert_seitFormatiert() ?></td>
            <td>
                <a href="<?php echo $this->urlFor('benutzer', 'editieren') ?>?id=<?php echo $b->getId() ?>">editieren</a>
            </td>
            <td>
                <a href="<?php echo $this->urlFor('benutzer', 'loeschen') ?>?id=<?php echo $b->getId() ?>">löschen</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php require 'views/partials/pager.phtml' ?>

<p>
    <a href="<?php echo $this->urlFor('benutzer', 'neu') ?>">Neuen Benutzer eintragen</a>
</p>

