<h2>Willkommen in der Seminarverwaltung</h2>
<p>Hier können Sie:</p>
<ul class="text">
    <li>Seminare bearbeiten</li>
    <li>Seminartermine bearbeiten</li>
    <li>Benutzer bearbeiten</li>
    <li>Die API-Dokumentation lesen</li>
</ul>


<?php if (! \library\Auth::isLoggedIn()): ?>
    <h3>Login:</h3>
    <form action="<?php echo $this->urlFor('auth', 'login') ?>" method="post">
        E-Mail-Adresse:
        <input type="text" name="email" /><br />
        Passwort:
        <input type="password" name="passwort"<br />
        <input type="submit" value="einloggen" />
    </form>
<?php endif; ?>
