<?php require 'views/partials/pager.phtml' ?>

<table border="1" style="width: 100%">
    <tr>
        <th><a href="<?php echo $this->urlFor('seminar', 'index') ?>?order_by=titel&asc=<?php echo $asc ? 'false' : 'true' ?>">Titel</a></th>
        <th><a href="<?php echo $this->urlFor('seminar', 'index') ?>?order_by=beschreibung&asc=<?php echo $asc ? 'false' : 'true' ?>">Beschreibung</a></th>
        <th><a href="<?php echo $this->urlFor('seminar', 'index') ?>?order_by=preis&asc=<?php echo $asc ? 'false' : 'true' ?>">Preis (in Euro)</a></th>
        <th><a href="<?php echo $this->urlFor('seminar', 'index') ?>?order_by=kategorie&asc=<?php echo $asc ? 'false' : 'true' ?>">Kategorie</a></th>
        <th>editieren</th>
        <th>löschen</th>
    </tr>
    <?php foreach ($seminare as $s): ?>
        <tr>
            <td><?php echo $s->getTitel() ?></td>
            <td><?php echo $s->getBeschreibungFormatiert() ?></td>
            <td><?php echo $s->getPreis() ?> €</td>
            <td><?php echo $s->getKategorie() ?></td>
            <td>
                <a href="<?php echo $this->urlFor('seminar', 'editieren') ?>?id=<?php echo $s->getId() ?>">editieren</a>
            </td>
            <td>
                <a href="<?php echo $this->urlFor('seminar', 'loeschen') ?>?id=<?php echo $s->getId() ?>">löschen</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<?php require 'views/partials/pager.phtml' ?>

<p>
    <a href="<?php echo $this->urlFor('seminar', 'neu') ?>">Neues Seminar eintragen</a>
</p>
