<?php if (! $seminartermin->isValid() ): ?>
    <ul>
        <?php foreach ($seminartermin->getErrors() as $e): ?>
            <li style="color: #ff0000"><?php echo $e ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<form action="<?php echo $save_url ?>" method="post">
    <input type="hidden" name="id" value="<?php echo $seminartermin->getId() ?>" />
    
    Seminar: 
    <select name="seminar_id">
        <?php foreach ($seminare as $s): ?>
            <option value="<?php echo $s->getId(); ?>" <?php if ($s->getId() == $seminar_id) echo 'selected="selected"' ?> ><?php echo $s->getTitel(); ?></option>
        <?php endforeach; ?>
    </select><br />

    Raum: <input type="text" name="raum" value="<?php echo $seminartermin->getRaum() ?>" /><br />
    Beginn (YYYY-MM-DD): <input type="text" name="beginn" value="<?php echo $seminartermin->getBeginn() ?>" /><br />
    Ende (YYYY-MM-DD): <input type="text" name="ende" value="<?php echo $seminartermin->getEnde() ?>" /><br />
    <input type="submit" value="Seminartermin speichern" />
</form>

<h2>Teilnehmer des Seminars</h2>
<table border="1">
    <tr>
        <th>Vorname</th>
        <th>Name</th>
        <th>E-Mail-Adresse</th>
        <th>löschen</th>
    </tr>
    <?php foreach ($teilnehmer as $t): ?>
        <tr>
            <td><?php echo $t->getVorname() ?></td>
            <td><?php echo $t->getName() ?></td>
            <td><?php echo $t->getEmail() ?></td>
            <td>
                <a href="<?php echo $this->urlFor('seminartermin', 'teilnehmer_entfernen') ?>?seminartermin_id=<?php echo $seminartermin->getId() ?>&teilnehmer_id=<?php echo $t->getId() ?>">
                    löschen
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<p><a href="<?php echo $this->urlFor('seminartermin', 'teilnehmer_hinzufuegen') ?>?seminartermin_id=<?php echo $seminartermin->getId() ?>">
    Teilnehmer hinzufügen
</a></p>

<p><a href="<?php echo $this->urlFor('seminartermin') ?>">zurück zur Übersicht</a>
