<table border="1">
    <tr>
        <th>Seminar</th>
        <th>Raum</th>
        <th>Beginn</th>
        <th>Ende</th>
        <th>Dauer</th>
        <th>Anzahl Teilnehmer</th>
        <th>editieren</th>
        <th>löschen</th>
    </tr>
    <?php foreach ($seminartermine as $s): ?>
        <tr>
            <td><?php echo $s->getSeminar()->getTitel() ?></td>
            <td><?php echo $s->getRaum() ?></td>
            <td><?php echo $s->getBeginnFormatiert() ?></td>
            <td><?php echo $s->getEndeFormatiert() ?></td>
            <td><?php echo $s->getDauer()->format('%d') + 1 ?> Tag(e)</td>
            <td><?php echo $s->countTeilnehmer() ?></td>
            <td>
                <a href="<?php echo $this->urlFor('seminartermin', 'editieren') ?>?id=<?php echo $s->getId() ?>">editieren</a>
            </td>
            <td>
                <?php if( $s->countTeilnehmer() === 0 ): ?>
                    <a href="<?php echo $this->urlFor('seminartermin', 'loeschen') ?>?id=<?php echo $s->getId() ?>">löschen</a>
                <?php else: ?>
                    nicht möglich
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<p>
    <a href="<?php echo $this->urlFor('seminartermin', 'neu') ?>">Neuen Seminartermin eintragen</a>
</p>
